version: "3"

services:
  frontend:
    image: gitlab.local:5000/root/docker/frontend:${CI_COMMIT_SHA}
    container_name: frontend
    deploy:
      replicas: 1
    command: npm run start 
    ports: 
      - "4200:4200"
    networks:
      - hatka
    volumes:
      - frontend_data:/usr/src/app/src/frontend

  api:
    image: gitlab.local:5000/root/docker/api:${CI_COMMIT_SHA}
    container_name: api
    deploy:
      replicas: 1
    command: npm run start
    environment:
      - PORT=3000
    depends_on:
      - api_db
    volumes:
      - api_data:/usr/src/app/src/backend
    ports:
      - "3000:3000"
    networks:
      - hatka

  api_db:
    image: mariadb:10.7.4
    container_name: database_hatka
    deploy:
      replicas: 1
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test"
    volumes:
      - db_data:/db # shared DB folder
      - db_sql_data:/var/lib/mysql # database data
      - db_ini_data:/etc/mysql/conf.d/my.ini # config file
      - db_sh_data:/docker-entrypoint-initdb.d/init.sh # init
    ports:
      - "3306:3306"
    networks:
      - hatka

  
  nginx:
    image: gitlab.local:5000/root/docker/nginx:${CI_COMMIT_SHA}
    container_name: nginx
    deploy:
      replicas: 1
      placement:
          constraints: [node.role == manager]
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - hatka

volumes:
    frontend_data:
    api_data:
    db_data:
    db_sql_data:
    db_ini_data:
    db_sh_data:
    nginx_data:

networks:
  hatka:
